------------------Roles-------------
INSERT INTO roles(active, created_at, deleted_at, updated_at, role_id, create_by, delete_by, update_by, role_description, role_name) VALUES (true, '2024-08-22 14:00:00', null, null, '2326ec2c-4f97-4007-b52c-ba5561b434b9', '177b61e6-51ad-4185-894b-dc7495599cfc', null, null, 'usuario(cliente)', 'ROLE_USER');

INSERT INTO roles(active, created_at, deleted_at, updated_at, role_id, create_by, delete_by, update_by, role_description, role_name) VALUES (true, '2024-08-22 14:00:00', null, null, 'a020e421-d5fb-48e9-a984-62c04a0b22a2', '177b61e6-51ad-4185-894b-dc7495599cfc', null, null, 'administrador de la clinica', 'ROLE_ADMIN');

INSERT INTO roles(active, created_at, deleted_at, updated_at, role_id, create_by, delete_by, update_by, role_description, role_name) VALUES (true, '2024-08-22 14:00:00', null, null, '9c765b7d-9eec-421b-85c6-6d53bcd002da', '177b61e6-51ad-4185-894b-dc7495599cfc', null, null, 'especialistas', 'ROLE_SPECIALIST');

------------------User--------------------
INSERT INTO users(active, created_at, deleted_at, updated_at, create_by, delete_by, update_by, user_id, password, username) VALUES (true, '2024-08-24', null, null, 'd0b4c3d8-6beb-40b7-871b-177ee20627cb', null, null, '895769e3-1828-40c6-8b97-257f82851375', '$2y$10$j8O64cfWP70WHySKmYFnbuBwIBP.XuXmlPKiTA9p56vCZUwNz7gnm', 'admin@gmail.com');

-----------------User-role----------------
INSERT INTO user_role(role_id, user_id)VALUES ('2326ec2c-4f97-4007-b52c-ba5561b434b9', '895769e3-1828-40c6-8b97-257f82851375');




-- Pais
INSERT INTO countries(country_id, country_name) VALUES (1, 'Argentina');

-- Provincias
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 1, 'Ciudad Autonoma de Buenos Aires');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 2, 'Neuquen');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 3, 'San Luis');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 4, 'Santa Fe');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 5, 'La Rioja');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 6, 'Catamarca');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 7, 'Tucuman');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 8, 'Chaco');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 9, 'Formosa');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 10, 'Santa Cruz');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 11, 'Chubut');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 12, 'Mendoza');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 13, 'Entre Ríos');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 14, 'San Juan');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 15, 'Jujuy');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 16, 'Santiago del Estero');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 17, 'Río Negro');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 18, 'Corrientes');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 19, 'Misiones');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 20, 'Salta');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 21, 'Córdoba');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 22, 'Buenos Aires');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 23, 'La Pampa');
INSERT INTO departments(country_id, department_id, department_name) VALUES (1, 24, 'Tierra del Fuego, Antartida e Islas del Atlantico Sur');


INSERT INTO cities(city_id, department_id, city_name) VALUES (1, 6, 'Adolfo Gonzales Chaves');
INSERT INTO cities(city_id, department_id, city_name) VALUES (2, 13, 'Concordia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (3, 13, 'Federal');
INSERT INTO cities(city_id, department_id, city_name) VALUES (4, 13, 'Gualeguaychú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (5, 13, 'Islas del Ibicuy');
INSERT INTO cities(city_id, department_id, city_name) VALUES (6, 13, 'Victoria');
INSERT INTO cities(city_id, department_id, city_name) VALUES (7, 13, 'Diamante');
INSERT INTO cities(city_id, department_id, city_name) VALUES (8, 13, 'Uruguay');
INSERT INTO cities(city_id, department_id, city_name) VALUES (9, 13, 'Paraná');
INSERT INTO cities(city_id, department_id, city_name) VALUES (10, 6, 'Saladillo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (11, 6, 'Las Flores');
INSERT INTO cities(city_id, department_id, city_name) VALUES (12, 6, 'Rojas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (13, 6, 'Escobar');
INSERT INTO cities(city_id, department_id, city_name) VALUES (14, 6, 'José C. Paz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (15, 6, 'Bahía Blanca');
INSERT INTO cities(city_id, department_id, city_name) VALUES (16, 6, 'San Antonio de Areco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (17, 6, 'Maipú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (18, 6, 'General Alvarado');
INSERT INTO cities(city_id, department_id, city_name) VALUES (19, 6, 'General Pueyrredón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (20, 6, 'Mar Chiquita');
INSERT INTO cities(city_id, department_id, city_name) VALUES (21, 6, 'Villa Gesell');
INSERT INTO cities(city_id, department_id, city_name) VALUES (22, 6, 'Pinamar');
INSERT INTO cities(city_id, department_id, city_name) VALUES (23, 6, 'General Lavalle');
INSERT INTO cities(city_id, department_id, city_name) VALUES (24, 6, 'La Costa');
INSERT INTO cities(city_id, department_id, city_name) VALUES (25, 6, 'Magdalena');
INSERT INTO cities(city_id, department_id, city_name) VALUES (26, 18, 'Sauce');
INSERT INTO cities(city_id, department_id, city_name) VALUES (27, 6, 'Vicente López');
INSERT INTO cities(city_id, department_id, city_name) VALUES (28, 20, 'La Viña');
INSERT INTO cities(city_id, department_id, city_name) VALUES (29, 6, 'Rauch');
INSERT INTO cities(city_id, department_id, city_name) VALUES (30, 20, 'Metán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (31, 20, 'Molinos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (32, 22, 'O Higgins');
INSERT INTO cities(city_id, department_id, city_name) VALUES (33, 6, 'Moreno');
INSERT INTO cities(city_id, department_id, city_name) VALUES (34, 6, 'La Matanza');
INSERT INTO cities(city_id, department_id, city_name) VALUES (35, 6, 'Tandil');
INSERT INTO cities(city_id, department_id, city_name) VALUES (36, 6, 'Coronel Suárez');
INSERT INTO cities(city_id, department_id, city_name) VALUES (37, 5, 'Chamical');
INSERT INTO cities(city_id, department_id, city_name) VALUES (38, 11, 'Futaleufú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (39, 11, 'Río Chico');
INSERT INTO cities(city_id, department_id, city_name) VALUES (40, 17, 'San Antonio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (41, 16, 'Alberdi');
INSERT INTO cities(city_id, department_id, city_name) VALUES (42, 16, 'Juan Felipe Ibarra');
INSERT INTO cities(city_id, department_id, city_name) VALUES (43, 16, 'General Taboada');
INSERT INTO cities(city_id, department_id, city_name) VALUES (44, 6, 'Salliqueló');
INSERT INTO cities(city_id, department_id, city_name) VALUES (45, 6, 'Berazategui');
INSERT INTO cities(city_id, department_id, city_name) VALUES (46, 20, 'General Güemes');
INSERT INTO cities(city_id, department_id, city_name) VALUES (47, 20, 'San Carlos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (48, 6, 'General Paz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (49, 6, 'General Guido');
INSERT INTO cities(city_id, department_id, city_name) VALUES (50, 6, 'General Juan Madariaga');
INSERT INTO cities(city_id, department_id, city_name) VALUES (51, 11, 'Lago Argentino');
INSERT INTO cities(city_id, department_id, city_name) VALUES (52, 16, 'Rivadavia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (53, 16, 'Ojo de Agua');
INSERT INTO cities(city_id, department_id, city_name) VALUES (54, 16, 'Choya');
INSERT INTO cities(city_id, department_id, city_name) VALUES (55, 1, 'Gobernador Dupuy');
INSERT INTO cities(city_id, department_id, city_name) VALUES (56, 20, 'Cachi');
INSERT INTO cities(city_id, department_id, city_name) VALUES (57, 20, 'Chicoana');
INSERT INTO cities(city_id, department_id, city_name) VALUES (58, 11, 'Gaiman');
INSERT INTO cities(city_id, department_id, city_name) VALUES (59, 11, 'Rawson');
INSERT INTO cities(city_id, department_id, city_name) VALUES (60, 5, 'General Lamadrid');
INSERT INTO cities(city_id, department_id, city_name) VALUES (61, 1, 'Ayacucho');
INSERT INTO cities(city_id, department_id, city_name) VALUES (62, 22, '12 de Octubre');
INSERT INTO cities(city_id, department_id, city_name) VALUES (63, 14, 'Tulumba');
INSERT INTO cities(city_id, department_id, city_name) VALUES (64, 14, 'Cruz del Eje');
INSERT INTO cities(city_id, department_id, city_name) VALUES (65, 14, 'Punilla');
INSERT INTO cities(city_id, department_id, city_name) VALUES (66, 2, 'Comuna 6');
INSERT INTO cities(city_id, department_id, city_name) VALUES (67, 23, 'Santa Rosa');
INSERT INTO cities(city_id, department_id, city_name) VALUES (68, 22, 'General Güemes');
INSERT INTO cities(city_id, department_id, city_name) VALUES (69, 5, 'General Ortiz de Ocampo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (70, 14, 'General Roca');
INSERT INTO cities(city_id, department_id, city_name) VALUES (71, 9, 'Pilagás');
INSERT INTO cities(city_id, department_id, city_name) VALUES (72, 9, 'Laishi');
INSERT INTO cities(city_id, department_id, city_name) VALUES (73, 23, 'Rivadavia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (74, 6, 'Tornquist');
INSERT INTO cities(city_id, department_id, city_name) VALUES (75, 23, 'La Paz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (76, 6, 'Coronel Pringles');
INSERT INTO cities(city_id, department_id, city_name) VALUES (77, 17, 'Conesa');
INSERT INTO cities(city_id, department_id, city_name) VALUES (78, 6, 'Villarino');
INSERT INTO cities(city_id, department_id, city_name) VALUES (79, 9, 'Pirané');
INSERT INTO cities(city_id, department_id, city_name) VALUES (80, 6, 'General Pinto');
INSERT INTO cities(city_id, department_id, city_name) VALUES (81, 6, 'San Cayetano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (82, 6, 'Tres Arroyos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (83, 6, 'Coronel Dorrego');
INSERT INTO cities(city_id, department_id, city_name) VALUES (84, 6, 'Necochea');
INSERT INTO cities(city_id, department_id, city_name) VALUES (85, 5, 'Independencia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (86, 6, 'Chascomús');
INSERT INTO cities(city_id, department_id, city_name) VALUES (87, 6, 'Punta Indio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (88, 15, 'El Carmen');
INSERT INTO cities(city_id, department_id, city_name) VALUES (89, 14, 'Santa María');
INSERT INTO cities(city_id, department_id, city_name) VALUES (90, 17, 'Valcheta');
INSERT INTO cities(city_id, department_id, city_name) VALUES (91, 5, 'Arauco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (92, 6, 'Lezama');
INSERT INTO cities(city_id, department_id, city_name) VALUES (93, 6, 'Campana');
INSERT INTO cities(city_id, department_id, city_name) VALUES (94, 11, 'Magallanes');
INSERT INTO cities(city_id, department_id, city_name) VALUES (95, 11, 'Corpen Aike');
INSERT INTO cities(city_id, department_id, city_name) VALUES (96, 14, 'Minas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (97, 14, 'San Alberto');
INSERT INTO cities(city_id, department_id, city_name) VALUES (98, 14, 'Río Segundo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (99, 14, 'San Justo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (100, 14, 'Unión');
INSERT INTO cities(city_id, department_id, city_name) VALUES (101, 14, 'Tercero Arriba');
INSERT INTO cities(city_id, department_id, city_name) VALUES (102, 20, 'Cerrillos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (103, 14, 'Río Cuarto');
INSERT INTO cities(city_id, department_id, city_name) VALUES (104, 23, 'Tupungato');
INSERT INTO cities(city_id, department_id, city_name) VALUES (105, 17, '9 de Julio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (106, 17, 'Ñorquinco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (107, 23, 'San Rafael');
INSERT INTO cities(city_id, department_id, city_name) VALUES (108, 20, 'Anta');
INSERT INTO cities(city_id, department_id, city_name) VALUES (109, 2, 'Picún Leufú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (110, 2, 'Zapala');
INSERT INTO cities(city_id, department_id, city_name) VALUES (111, 17, '25 de Mayo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (112, 11, 'Telsen');
INSERT INTO cities(city_id, department_id, city_name) VALUES (113, 17, 'Pilcaniyeu');
INSERT INTO cities(city_id, department_id, city_name) VALUES (114, 6, 'Adolfo Alsina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (115, 23, 'General Alvear');
INSERT INTO cities(city_id, department_id, city_name) VALUES (116, 20, 'La Caldera');
INSERT INTO cities(city_id, department_id, city_name) VALUES (117, 22, 'Sargento Cabral');
INSERT INTO cities(city_id, department_id, city_name) VALUES (118, 6, 'Pellegrini');
INSERT INTO cities(city_id, department_id, city_name) VALUES (119, 2, 'Aluminé');
INSERT INTO cities(city_id, department_id, city_name) VALUES (120, 20, 'Iruya');
INSERT INTO cities(city_id, department_id, city_name) VALUES (121, 2, 'Lácar');
INSERT INTO cities(city_id, department_id, city_name) VALUES (122, 10, 'Fray Mamerto Esquiú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (123, 10, 'Valle Viejo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (124, 18, 'San Cosme');
INSERT INTO cities(city_id, department_id, city_name) VALUES (125, 11, 'Sarmiento');
INSERT INTO cities(city_id, department_id, city_name) VALUES (126, 2, 'Comuna 1');
INSERT INTO cities(city_id, department_id, city_name) VALUES (127, 2, 'Comuna 4');
INSERT INTO cities(city_id, department_id, city_name) VALUES (128, 17, 'El Cuy');
INSERT INTO cities(city_id, department_id, city_name) VALUES (129, 23, 'Las Heras');
INSERT INTO cities(city_id, department_id, city_name) VALUES (130, 22, 'Tapenagá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (131, 23, 'Lavalle');
INSERT INTO cities(city_id, department_id, city_name) VALUES (132, 23, 'Malargüe');
INSERT INTO cities(city_id, department_id, city_name) VALUES (133, 14, 'Presidente Roque Sáenz Peña');
INSERT INTO cities(city_id, department_id, city_name) VALUES (134, 2, 'Catán Lil');
INSERT INTO cities(city_id, department_id, city_name) VALUES (135, 22, 'Presidencia de la Plaza');
INSERT INTO cities(city_id, department_id, city_name) VALUES (136, 2, 'Comuna 5');
INSERT INTO cities(city_id, department_id, city_name) VALUES (137, 18, 'Esquina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (138, 24, 'Ushuaia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (139, 10, 'Antofagasta de la Sierra');
INSERT INTO cities(city_id, department_id, city_name) VALUES (140, 6, 'Ensenada');
INSERT INTO cities(city_id, department_id, city_name) VALUES (141, 1, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (142, 4, 'Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (143, 6, 'Pergamino');
INSERT INTO cities(city_id, department_id, city_name) VALUES (144, 6, 'Puán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (145, 6, 'General Villegas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (146, 2, 'Comuna 12');
INSERT INTO cities(city_id, department_id, city_name) VALUES (147, 4, 'General Obligado');
INSERT INTO cities(city_id, department_id, city_name) VALUES (148, 4, 'Vera');
INSERT INTO cities(city_id, department_id, city_name) VALUES (149, 4, '9 de Julio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (150, 17, 'Adolfo Alsina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (151, 22, 'Quitilipi');
INSERT INTO cities(city_id, department_id, city_name) VALUES (152, 11, 'Güer Aike');
INSERT INTO cities(city_id, department_id, city_name) VALUES (153, 10, 'Capayán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (154, 1, 'Burruyacú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (155, 4, 'San Jerónimo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (156, 22, 'Independencia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (157, 18, 'Curuzú Cuatiá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (158, 23, 'Luján de Cuyo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (159, 10, 'Tinogasta');
INSERT INTO cities(city_id, department_id, city_name) VALUES (160, 2, 'Comuna 7');
INSERT INTO cities(city_id, department_id, city_name) VALUES (161, 23, 'Hucal');
INSERT INTO cities(city_id, department_id, city_name) VALUES (162, 18, 'Itatí');
INSERT INTO cities(city_id, department_id, city_name) VALUES (163, 2, 'Comuna 10');
INSERT INTO cities(city_id, department_id, city_name) VALUES (164, 23, 'Caleu Caleu');
INSERT INTO cities(city_id, department_id, city_name) VALUES (165, 23, 'Lihuel Calel');
INSERT INTO cities(city_id, department_id, city_name) VALUES (720, 23, 'Curacó');
INSERT INTO cities(city_id, department_id, city_name) VALUES (167, 2, 'Confluencia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (168, 2, 'Picunches');
INSERT INTO cities(city_id, department_id, city_name) VALUES (169, 2, 'Añelo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (170, 2, 'Loncopué');
INSERT INTO cities(city_id, department_id, city_name) VALUES (171, 2, 'Ñorquín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (172, 2, 'Pehuenches');
INSERT INTO cities(city_id, department_id, city_name) VALUES (173, 2, 'Comuna 11');
INSERT INTO cities(city_id, department_id, city_name) VALUES (174, 19, 'Montecarlo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (175, 19, 'Eldorado');
INSERT INTO cities(city_id, department_id, city_name) VALUES (176, 19, 'San Pedro');
INSERT INTO cities(city_id, department_id, city_name) VALUES (177, 24, 'Antártida Argentina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (178, 2, 'Minas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (179, 2, 'Chos Malal');
INSERT INTO cities(city_id, department_id, city_name) VALUES (180, 11, 'Cushamen');
INSERT INTO cities(city_id, department_id, city_name) VALUES (181, 11, 'Lago Buenos Aires');
INSERT INTO cities(city_id, department_id, city_name) VALUES (182, 17, 'Pichi Mahuida');
INSERT INTO cities(city_id, department_id, city_name) VALUES (183, 16, 'San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (184, 15, 'Yavi');
INSERT INTO cities(city_id, department_id, city_name) VALUES (185, 15, 'Santa Catalina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (186, 15, 'San Pedro');
INSERT INTO cities(city_id, department_id, city_name) VALUES (187, 15, 'Valle Grande');
INSERT INTO cities(city_id, department_id, city_name) VALUES (188, 9, 'Patiño');
INSERT INTO cities(city_id, department_id, city_name) VALUES (189, 9, 'Bermejo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (190, 15, 'Susques');
INSERT INTO cities(city_id, department_id, city_name) VALUES (191, 9, 'Matacos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (192, 20, 'Los Andes');
INSERT INTO cities(city_id, department_id, city_name) VALUES (193, 20, 'Orán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (194, 15, 'Tilcara');
INSERT INTO cities(city_id, department_id, city_name) VALUES (195, 15, 'Palpalá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (196, 23, 'Loventué');
INSERT INTO cities(city_id, department_id, city_name) VALUES (197, 11, 'Río Senguer');
INSERT INTO cities(city_id, department_id, city_name) VALUES (198, 17, 'Bariloche');
INSERT INTO cities(city_id, department_id, city_name) VALUES (199, 2, 'Huiliches');
INSERT INTO cities(city_id, department_id, city_name) VALUES (200, 23, 'Limay Mahuida');
INSERT INTO cities(city_id, department_id, city_name) VALUES (201, 23, 'Puelén');
INSERT INTO cities(city_id, department_id, city_name) VALUES (202, 23, 'Chalileo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (203, 23, 'Chical Co');
INSERT INTO cities(city_id, department_id, city_name) VALUES (204, 16, 'Quebrachos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (205, 18, 'Monte Caseros');
INSERT INTO cities(city_id, department_id, city_name) VALUES (206, 22, 'Mayor Luis J. Fontana');
INSERT INTO cities(city_id, department_id, city_name) VALUES (207, 22, 'Fray Justo Santa María de Oro');
INSERT INTO cities(city_id, department_id, city_name) VALUES (208, 5, 'General Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (209, 4, 'Las Colonias');
INSERT INTO cities(city_id, department_id, city_name) VALUES (210, 4, 'San Justo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (211, 4, 'San Cristóbal');
INSERT INTO cities(city_id, department_id, city_name) VALUES (212, 4, 'San Javier');
INSERT INTO cities(city_id, department_id, city_name) VALUES (213, 23, 'Chapaleufú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (214, 23, 'Realicó');
INSERT INTO cities(city_id, department_id, city_name) VALUES (215, 23, 'Maracó');
INSERT INTO cities(city_id, department_id, city_name) VALUES (216, 23, 'Trenel');
INSERT INTO cities(city_id, department_id, city_name) VALUES (217, 16, 'Copo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (218, 23, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (219, 15, 'Santa Bárbara');
INSERT INTO cities(city_id, department_id, city_name) VALUES (220, 22, 'Almirante Brown');
INSERT INTO cities(city_id, department_id, city_name) VALUES (221, 20, 'Rosario de la Frontera');
INSERT INTO cities(city_id, department_id, city_name) VALUES (222, 2, 'Collón Curá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (223, 2, 'Comuna 3');
INSERT INTO cities(city_id, department_id, city_name) VALUES (224, 6, 'San Fernando');
INSERT INTO cities(city_id, department_id, city_name) VALUES (225, 6, 'Tigre');
INSERT INTO cities(city_id, department_id, city_name) VALUES (226, 10, 'Santa María');
INSERT INTO cities(city_id, department_id, city_name) VALUES (227, 10, 'Santa Rosa');
INSERT INTO cities(city_id, department_id, city_name) VALUES (228, 10, 'La Paz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (229, 16, 'Río Hondo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (230, 5, 'Vinchina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (231, 5, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (232, 14, 'Río Seco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (233, 17, 'Avellaneda');
INSERT INTO cities(city_id, department_id, city_name) VALUES (234, 17, 'General Roca');
INSERT INTO cities(city_id, department_id, city_name) VALUES (235, 1, 'Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (236, 2, 'Los Lagos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (237, 10, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (238, 10, 'Ancasti');
INSERT INTO cities(city_id, department_id, city_name) VALUES (239, 10, 'Pomán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (240, 2, 'Comuna 2');
INSERT INTO cities(city_id, department_id, city_name) VALUES (241, 22, '9 de Julio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (242, 14, 'Pocho');
INSERT INTO cities(city_id, department_id, city_name) VALUES (243, 6, 'Ezeiza');
INSERT INTO cities(city_id, department_id, city_name) VALUES (244, 10, 'Andalgalá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (245, 10, 'Ambato');
INSERT INTO cities(city_id, department_id, city_name) VALUES (246, 2, 'Comuna 8');
INSERT INTO cities(city_id, department_id, city_name) VALUES (247, 16, 'Guasayán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (248, 10, 'Paclín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (249, 10, 'El Alto');
INSERT INTO cities(city_id, department_id, city_name) VALUES (250, 14, 'Sobremonte');
INSERT INTO cities(city_id, department_id, city_name) VALUES (251, 24, 'Río Grande');
INSERT INTO cities(city_id, department_id, city_name) VALUES (252, 2, 'Comuna 13');
INSERT INTO cities(city_id, department_id, city_name) VALUES (253, 16, 'Banda');
INSERT INTO cities(city_id, department_id, city_name) VALUES (254, 11, 'Paso de Indios');
INSERT INTO cities(city_id, department_id, city_name) VALUES (255, 14, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (256, 11, 'Mártires');
INSERT INTO cities(city_id, department_id, city_name) VALUES (257, 16, 'Sarmiento');
INSERT INTO cities(city_id, department_id, city_name) VALUES (258, 11, 'Deseado');
INSERT INTO cities(city_id, department_id, city_name) VALUES (259, 11, 'Languiñeo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (260, 16, 'Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (261, 16, 'Aguirre');
INSERT INTO cities(city_id, department_id, city_name) VALUES (262, 22, 'Maipú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (263, 23, 'San Carlos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (264, 23, 'Tunuyán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (265, 16, 'Robles');
INSERT INTO cities(city_id, department_id, city_name) VALUES (266, 16, 'Loreto');
INSERT INTO cities(city_id, department_id, city_name) VALUES (267, 23, 'Catriló');
INSERT INTO cities(city_id, department_id, city_name) VALUES (268, 16, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (269, 2, 'Comuna 14');
INSERT INTO cities(city_id, department_id, city_name) VALUES (270, 13, 'Colón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (271, 13, 'Villaguay');
INSERT INTO cities(city_id, department_id, city_name) VALUES (272, 6, 'Castelli');
INSERT INTO cities(city_id, department_id, city_name) VALUES (273, 13, 'San Salvador');
INSERT INTO cities(city_id, department_id, city_name) VALUES (274, 10, 'Belén');
INSERT INTO cities(city_id, department_id, city_name) VALUES (275, 6, 'Almirante Brown');
INSERT INTO cities(city_id, department_id, city_name) VALUES (276, 13, 'Nogoyá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (277, 13, 'Tala');
INSERT INTO cities(city_id, department_id, city_name) VALUES (278, 13, 'Gualeguay');
INSERT INTO cities(city_id, department_id, city_name) VALUES (279, 13, 'Federación');
INSERT INTO cities(city_id, department_id, city_name) VALUES (280, 13, 'La Paz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (281, 13, 'Feliciano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (282, 6, 'Presidente Perón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (283, 6, 'Junín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (284, 6, 'Brandsen');
INSERT INTO cities(city_id, department_id, city_name) VALUES (285, 6, 'Chivilcoy');
INSERT INTO cities(city_id, department_id, city_name) VALUES (286, 6, 'Alberti');
INSERT INTO cities(city_id, department_id, city_name) VALUES (287, 6, 'Bragado');
INSERT INTO cities(city_id, department_id, city_name) VALUES (288, 6, 'General Las Heras');
INSERT INTO cities(city_id, department_id, city_name) VALUES (289, 6, 'Carlos Casares');
INSERT INTO cities(city_id, department_id, city_name) VALUES (290, 6, 'Marcos Paz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (291, 6, 'General Viamonte');
INSERT INTO cities(city_id, department_id, city_name) VALUES (292, 6, 'Carlos Tejedor');
INSERT INTO cities(city_id, department_id, city_name) VALUES (293, 6, '25 de Mayo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (294, 6, '9 de Julio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (295, 6, 'Pehuajó');
INSERT INTO cities(city_id, department_id, city_name) VALUES (296, 6, 'Tapalqué');
INSERT INTO cities(city_id, department_id, city_name) VALUES (297, 6, 'Trenque Lauquen');
INSERT INTO cities(city_id, department_id, city_name) VALUES (298, 6, 'General Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (299, 6, 'Monte');
INSERT INTO cities(city_id, department_id, city_name) VALUES (300, 6, 'Roque Pérez');
INSERT INTO cities(city_id, department_id, city_name) VALUES (301, 6, 'Olavarría');
INSERT INTO cities(city_id, department_id, city_name) VALUES (302, 6, 'Merlo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (303, 19, 'Cainguás');
INSERT INTO cities(city_id, department_id, city_name) VALUES (304, 24, 'Islas del Atlántico Sur');
INSERT INTO cities(city_id, department_id, city_name) VALUES (305, 6, 'Esteban Echeverría');
INSERT INTO cities(city_id, department_id, city_name) VALUES (306, 6, 'Arrecifes');
INSERT INTO cities(city_id, department_id, city_name) VALUES (307, 6, 'Capitán Sarmiento');
INSERT INTO cities(city_id, department_id, city_name) VALUES (308, 15, 'Dr. Manuel Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (309, 6, 'Carmen de Areco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (310, 6, 'Salto');
INSERT INTO cities(city_id, department_id, city_name) VALUES (311, 6, 'Exaltación de la Cruz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (312, 6, 'San Miguel');
INSERT INTO cities(city_id, department_id, city_name) VALUES (313, 6, 'San Andrés de Giles');
INSERT INTO cities(city_id, department_id, city_name) VALUES (314, 6, 'Mercedes');
INSERT INTO cities(city_id, department_id, city_name) VALUES (315, 6, 'Pilar');
INSERT INTO cities(city_id, department_id, city_name) VALUES (316, 6, 'Luján');
INSERT INTO cities(city_id, department_id, city_name) VALUES (317, 1, 'Famaillá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (318, 6, 'Hurlingham');
INSERT INTO cities(city_id, department_id, city_name) VALUES (319, 6, 'Morón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (320, 6, 'Chacabuco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (321, 23, 'Junín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (322, 6, 'Malvinas Argentinas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (323, 6, 'Tres Lomas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (324, 6, 'Ayacucho');
INSERT INTO cities(city_id, department_id, city_name) VALUES (325, 6, 'Guaminí');
INSERT INTO cities(city_id, department_id, city_name) VALUES (326, 6, 'General San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (327, 6, 'Lincoln');
INSERT INTO cities(city_id, department_id, city_name) VALUES (328, 6, 'Laprida');
INSERT INTO cities(city_id, department_id, city_name) VALUES (329, 6, 'San Isidro');
INSERT INTO cities(city_id, department_id, city_name) VALUES (330, 6, 'Benito Juárez');
INSERT INTO cities(city_id, department_id, city_name) VALUES (331, 6, 'Colón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (332, 6, 'Ituzaingó');
INSERT INTO cities(city_id, department_id, city_name) VALUES (333, 6, 'General Rodríguez');
INSERT INTO cities(city_id, department_id, city_name) VALUES (334, 6, 'Suipacha');
INSERT INTO cities(city_id, department_id, city_name) VALUES (335, 6, 'Tres de Febrero');
INSERT INTO cities(city_id, department_id, city_name) VALUES (336, 5, 'General Felipe Varela');
INSERT INTO cities(city_id, department_id, city_name) VALUES (337, 6, 'Florencio Varela');
INSERT INTO cities(city_id, department_id, city_name) VALUES (338, 6, 'Navarro');
INSERT INTO cities(city_id, department_id, city_name) VALUES (339, 6, 'Cañuelas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (340, 16, 'Moreno');
INSERT INTO cities(city_id, department_id, city_name) VALUES (341, 22, 'Chacabuco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (342, 6, 'San Vicente');
INSERT INTO cities(city_id, department_id, city_name) VALUES (343, 6, 'Lobos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (344, 6, 'General Alvear');
INSERT INTO cities(city_id, department_id, city_name) VALUES (345, 6, 'Quilmes');
INSERT INTO cities(city_id, department_id, city_name) VALUES (346, 6, 'Pila');
INSERT INTO cities(city_id, department_id, city_name) VALUES (347, 6, 'General La Madrid');
INSERT INTO cities(city_id, department_id, city_name) VALUES (348, 6, 'Bolívar');
INSERT INTO cities(city_id, department_id, city_name) VALUES (349, 5, 'Castro Barros');
INSERT INTO cities(city_id, department_id, city_name) VALUES (350, 6, 'Balcarce');
INSERT INTO cities(city_id, department_id, city_name) VALUES (351, 6, 'Hipólito Yrigoyen');
INSERT INTO cities(city_id, department_id, city_name) VALUES (352, 23, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (353, 6, 'Dolores');
INSERT INTO cities(city_id, department_id, city_name) VALUES (354, 6, 'Azul');
INSERT INTO cities(city_id, department_id, city_name) VALUES (355, 6, 'Daireaux');
INSERT INTO cities(city_id, department_id, city_name) VALUES (356, 23, 'Godoy Cruz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (357, 20, 'Cafayate');
INSERT INTO cities(city_id, department_id, city_name) VALUES (358, 16, 'Figueroa');
INSERT INTO cities(city_id, department_id, city_name) VALUES (359, 6, 'Saavedra');
INSERT INTO cities(city_id, department_id, city_name) VALUES (360, 6, 'Monte Hermoso');
INSERT INTO cities(city_id, department_id, city_name) VALUES (361, 6, 'Lobería');
INSERT INTO cities(city_id, department_id, city_name) VALUES (362, 6, 'Berisso');
INSERT INTO cities(city_id, department_id, city_name) VALUES (363, 6, 'Tordillo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (364, 6, 'Zárate');
INSERT INTO cities(city_id, department_id, city_name) VALUES (365, 6, 'Ramallo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (366, 6, 'San Nicolás');
INSERT INTO cities(city_id, department_id, city_name) VALUES (367, 16, 'Salavina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (368, 16, 'Pellegrini');
INSERT INTO cities(city_id, department_id, city_name) VALUES (369, 16, 'Avellaneda');
INSERT INTO cities(city_id, department_id, city_name) VALUES (370, 22, '2 de Abril');
INSERT INTO cities(city_id, department_id, city_name) VALUES (371, 23, 'Guaymallén');
INSERT INTO cities(city_id, department_id, city_name) VALUES (372, 14, 'Juárez Celman');
INSERT INTO cities(city_id, department_id, city_name) VALUES (373, 20, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (374, 16, 'Silípica');
INSERT INTO cities(city_id, department_id, city_name) VALUES (375, 20, 'La Candelaria');
INSERT INTO cities(city_id, department_id, city_name) VALUES (376, 23, 'Rancul');
INSERT INTO cities(city_id, department_id, city_name) VALUES (377, 23, 'Maipú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (378, 20, 'Guachipas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (379, 23, 'Atreucó');
INSERT INTO cities(city_id, department_id, city_name) VALUES (380, 23, 'San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (381, 23, 'Guatraché');
INSERT INTO cities(city_id, department_id, city_name) VALUES (382, 5, 'Sanagasta');
INSERT INTO cities(city_id, department_id, city_name) VALUES (383, 23, 'Conhelo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (384, 19, 'Libertador General San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (385, 5, 'Rosario Vera Peñaloza');
INSERT INTO cities(city_id, department_id, city_name) VALUES (386, 18, 'San Miguel');
INSERT INTO cities(city_id, department_id, city_name) VALUES (387, 5, 'General Juan Facundo Quiroga');
INSERT INTO cities(city_id, department_id, city_name) VALUES (388, 5, 'Ángel Vicente Peñaloza');
INSERT INTO cities(city_id, department_id, city_name) VALUES (389, 18, 'Empedrado');
INSERT INTO cities(city_id, department_id, city_name) VALUES (390, 5, 'Chilecito');
INSERT INTO cities(city_id, department_id, city_name) VALUES (391, 23, 'Toay');
INSERT INTO cities(city_id, department_id, city_name) VALUES (392, 14, 'Colón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (393, 18, 'Ituzaingó');
INSERT INTO cities(city_id, department_id, city_name) VALUES (394, 5, 'Famatina');
INSERT INTO cities(city_id, department_id, city_name) VALUES (395, 4, 'General López');
INSERT INTO cities(city_id, department_id, city_name) VALUES (396, 4, 'Constitución');
INSERT INTO cities(city_id, department_id, city_name) VALUES (397, 4, 'Caseros');
INSERT INTO cities(city_id, department_id, city_name) VALUES (398, 4, 'Rosario');
INSERT INTO cities(city_id, department_id, city_name) VALUES (399, 4, 'San Lorenzo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (400, 4, 'Iriondo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (401, 6, 'Lanús');
INSERT INTO cities(city_id, department_id, city_name) VALUES (402, 5, 'General San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (403, 5, 'San Blas de Los Sauces');
INSERT INTO cities(city_id, department_id, city_name) VALUES (404, 15, 'San Antonio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (405, 15, 'Rinconada');
INSERT INTO cities(city_id, department_id, city_name) VALUES (406, 9, 'Ramón Lista');
INSERT INTO cities(city_id, department_id, city_name) VALUES (407, 20, 'La Poma');
INSERT INTO cities(city_id, department_id, city_name) VALUES (408, 11, 'Biedma');
INSERT INTO cities(city_id, department_id, city_name) VALUES (409, 18, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (410, 18, 'San Luis del Palmar');
INSERT INTO cities(city_id, department_id, city_name) VALUES (411, 9, 'Formosa');
INSERT INTO cities(city_id, department_id, city_name) VALUES (412, 9, 'Pilcomayo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (413, 11, 'Tehuelches');
INSERT INTO cities(city_id, department_id, city_name) VALUES (414, 11, 'Escalante');
INSERT INTO cities(city_id, department_id, city_name) VALUES (415, 14, 'Ischilín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (416, 14, 'Totoral');
INSERT INTO cities(city_id, department_id, city_name) VALUES (417, 14, 'General San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (418, 14, 'San Javier');
INSERT INTO cities(city_id, department_id, city_name) VALUES (419, 14, 'Río Primero');
INSERT INTO cities(city_id, department_id, city_name) VALUES (420, 14, 'Marcos Juárez');
INSERT INTO cities(city_id, department_id, city_name) VALUES (421, 22, 'General Donovan');
INSERT INTO cities(city_id, department_id, city_name) VALUES (422, 6, 'Leandro N. Alem');
INSERT INTO cities(city_id, department_id, city_name) VALUES (423, 22, 'Libertador General San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (424, 11, 'Gastre');
INSERT INTO cities(city_id, department_id, city_name) VALUES (425, 6, 'General Arenales');
INSERT INTO cities(city_id, department_id, city_name) VALUES (426, 22, 'Bermejo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (427, 14, 'Calamuchita');
INSERT INTO cities(city_id, department_id, city_name) VALUES (428, 1, 'Cruz Alta');
INSERT INTO cities(city_id, department_id, city_name) VALUES (429, 1, 'Lules');
INSERT INTO cities(city_id, department_id, city_name) VALUES (430, 1, 'Yerba Buena');
INSERT INTO cities(city_id, department_id, city_name) VALUES (431, 1, 'Tafí Viejo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (432, 1, 'Libertador General San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (433, 1, 'Coronel Pringles');
INSERT INTO cities(city_id, department_id, city_name) VALUES (434, 1, 'Chacabuco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (435, 6, 'Rivadavia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (436, 6, 'Patagones');
INSERT INTO cities(city_id, department_id, city_name) VALUES (437, 1, 'Juan Martín de Pueyrredón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (438, 1, 'General Pedernera');
INSERT INTO cities(city_id, department_id, city_name) VALUES (439, 1, 'Trancas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (440, 1, 'Tafí del Valle');
INSERT INTO cities(city_id, department_id, city_name) VALUES (441, 2, 'Comuna 9');
INSERT INTO cities(city_id, department_id, city_name) VALUES (442, 1, 'Junín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (443, 16, 'Mitre');
INSERT INTO cities(city_id, department_id, city_name) VALUES (444, 16, 'Atamisqui');
INSERT INTO cities(city_id, department_id, city_name) VALUES (445, 18, 'Berón de Astrada');
INSERT INTO cities(city_id, department_id, city_name) VALUES (446, 24, 'Tolhuin');
INSERT INTO cities(city_id, department_id, city_name) VALUES (447, 19, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (448, 19, 'Candelaria');
INSERT INTO cities(city_id, department_id, city_name) VALUES (449, 16, 'Jiménez');
INSERT INTO cities(city_id, department_id, city_name) VALUES (450, 6, 'Coronel de Marina Leonardo Rosales');
INSERT INTO cities(city_id, department_id, city_name) VALUES (451, 6, 'Baradero');
INSERT INTO cities(city_id, department_id, city_name) VALUES (452, 6, 'San Pedro');
INSERT INTO cities(city_id, department_id, city_name) VALUES (453, 20, 'Santa Victoria');
INSERT INTO cities(city_id, department_id, city_name) VALUES (454, 20, 'General José de San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (455, 20, 'Rivadavia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (456, 20, 'Rosario de Lerma');
INSERT INTO cities(city_id, department_id, city_name) VALUES (457, 15, 'Ledesma');
INSERT INTO cities(city_id, department_id, city_name) VALUES (458, 15, 'Humahuaca');
INSERT INTO cities(city_id, department_id, city_name) VALUES (459, 15, 'Cochinoca');
INSERT INTO cities(city_id, department_id, city_name) VALUES (460, 15, 'Tumbaya');
INSERT INTO cities(city_id, department_id, city_name) VALUES (461, 6, 'Florentino Ameghino');
INSERT INTO cities(city_id, department_id, city_name) VALUES (462, 11, 'Florentino Ameghino');
INSERT INTO cities(city_id, department_id, city_name) VALUES (463, 1, 'La Cocha');
INSERT INTO cities(city_id, department_id, city_name) VALUES (464, 1, 'Graneros');
INSERT INTO cities(city_id, department_id, city_name) VALUES (465, 1, 'Juan Bautista Alberdi');
INSERT INTO cities(city_id, department_id, city_name) VALUES (466, 1, 'Río Chico');
INSERT INTO cities(city_id, department_id, city_name) VALUES (467, 1, 'Simoca');
INSERT INTO cities(city_id, department_id, city_name) VALUES (468, 1, 'Chicligasta');
INSERT INTO cities(city_id, department_id, city_name) VALUES (469, 1, 'Monteros');
INSERT INTO cities(city_id, department_id, city_name) VALUES (470, 1, 'Leales');
INSERT INTO cities(city_id, department_id, city_name) VALUES (471, 4, 'San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (472, 4, 'La Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (473, 19, 'General Manuel Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (474, 19, 'Guaraní');
INSERT INTO cities(city_id, department_id, city_name) VALUES (475, 19, 'Iguazú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (476, 19, '25 de Mayo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (477, 19, 'Oberá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (478, 4, 'Castellanos');
INSERT INTO cities(city_id, department_id, city_name) VALUES (479, 4, 'Garay');
INSERT INTO cities(city_id, department_id, city_name) VALUES (480, 23, 'Quemú Quemú');
INSERT INTO cities(city_id, department_id, city_name) VALUES (481, 19, 'San Ignacio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (482, 23, 'Utracán');
INSERT INTO cities(city_id, department_id, city_name) VALUES (483, 18, 'San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (484, 18, 'Paso de los Libres');
INSERT INTO cities(city_id, department_id, city_name) VALUES (485, 18, 'Goya');
INSERT INTO cities(city_id, department_id, city_name) VALUES (486, 18, 'Lavalle');
INSERT INTO cities(city_id, department_id, city_name) VALUES (487, 18, 'San Roque');
INSERT INTO cities(city_id, department_id, city_name) VALUES (488, 18, 'General Alvear');
INSERT INTO cities(city_id, department_id, city_name) VALUES (489, 18, 'Concepción');
INSERT INTO cities(city_id, department_id, city_name) VALUES (490, 18, 'Bella Vista');
INSERT INTO cities(city_id, department_id, city_name) VALUES (491, 18, 'Santo Tomé');
INSERT INTO cities(city_id, department_id, city_name) VALUES (492, 18, 'Saladas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (493, 18, 'General Paz');
INSERT INTO cities(city_id, department_id, city_name) VALUES (494, 19, 'Leandro N. Alem');
INSERT INTO cities(city_id, department_id, city_name) VALUES (495, 19, 'San Javier');
INSERT INTO cities(city_id, department_id, city_name) VALUES (496, 18, 'Mburucuyá');
INSERT INTO cities(city_id, department_id, city_name) VALUES (497, 19, 'Concepción');
INSERT INTO cities(city_id, department_id, city_name) VALUES (498, 19, 'Apóstoles');
INSERT INTO cities(city_id, department_id, city_name) VALUES (499, 22, '1° de Mayo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (500, 22, 'San Fernando');
INSERT INTO cities(city_id, department_id, city_name) VALUES (501, 22, 'San Lorenzo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (502, 6, 'Lomas de Zamora');
INSERT INTO cities(city_id, department_id, city_name) VALUES (503, 6, 'Avellaneda');
INSERT INTO cities(city_id, department_id, city_name) VALUES (504, 22, '25 de Mayo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (505, 22, 'General Belgrano');
INSERT INTO cities(city_id, department_id, city_name) VALUES (506, 22, 'Libertad');
INSERT INTO cities(city_id, department_id, city_name) VALUES (507, 22, 'Comandante Fernández');
INSERT INTO cities(city_id, department_id, city_name) VALUES (508, 2, 'Comuna 15');
INSERT INTO cities(city_id, department_id, city_name) VALUES (509, 14, 'Chimbas');
INSERT INTO cities(city_id, department_id, city_name) VALUES (510, 14, 'Capital');
INSERT INTO cities(city_id, department_id, city_name) VALUES (511, 14, 'Rivadavia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (512, 14, '9 de Julio');
INSERT INTO cities(city_id, department_id, city_name) VALUES (513, 14, 'Albardón');
INSERT INTO cities(city_id, department_id, city_name) VALUES (514, 14, 'Angaco');
INSERT INTO cities(city_id, department_id, city_name) VALUES (515, 14, 'Santa Lucía');
INSERT INTO cities(city_id, department_id, city_name) VALUES (516, 14, 'Rawson');
INSERT INTO cities(city_id, department_id, city_name) VALUES (517, 14, '25 de Mayo');
INSERT INTO cities(city_id, department_id, city_name) VALUES (518, 14, 'San Martín');
INSERT INTO cities(city_id, department_id, city_name) VALUES (519, 14, 'Pocito');
INSERT INTO cities(city_id, department_id, city_name) VALUES (520, 14, 'Zonda');
INSERT INTO cities(city_id, department_id, city_name) VALUES (521, 14, 'Ullum');
INSERT INTO cities(city_id, department_id, city_name) VALUES (522, 14, 'Sarmiento');
INSERT INTO cities(city_id, department_id, city_name) VALUES (523, 14, 'Calingasta');
INSERT INTO cities(city_id, department_id, city_name) VALUES (524, 14, 'Iglesia');
INSERT INTO cities(city_id, department_id, city_name) VALUES (525, 14, 'Jáchal');
INSERT INTO cities(city_id, department_id, city_name) VALUES (526, 14, 'Valle Fértil');
INSERT INTO cities(city_id, department_id, city_name) VALUES (527, 14, 'Caucete');
INSERT INTO cities(city_id, department_id, city_name) VALUES (528, 6, 'La Plata');
INSERT INTO cities(city_id, department_id, city_name) VALUES (529, 18, 'Mercedes');

-----------------Profile-------------------
INSERT INTO profiles(active, birth, created_at, deleted_at, city_id, updated_at, document_number, create_by, delete_by, profile_id, update_by, user_id, profile_name, profile_lastname, address, avatar_url, document_type) VALUES (true, '1975-06-25', '2024-08-24', null, 1, null, '81.544.670','895769e3-1828-40c6-8b97-257f82851375', null,'6097656c-e788-45cb-a41f-73d4e031ee60', null, '895769e3-1828-40c6-8b97-257f82851375', 'Susan', 'Martinez', 'Calle La Plata 259', null, 'DNI');


--------------Specialities-------------------
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 1, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Cardiologia', 'Cardiologia');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 2, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2',null, null,'Clinica medica', 'Clinica medica');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 3, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Nutricion', 'Nutricion');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 4, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Psicologia', 'Psicologia');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 5, null,'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Traumatologia', 'Traumatologia');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 6, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Neurología', 'Neurología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 7, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Inmunología', 'Inmunología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true,'2024-09-05', null, 8, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Oftalmología', 'Oftalmología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 9, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Ginecología', 'Ginecología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 10, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Dermatología', 'Dermatología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 11, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Pediatría', 'Pediatría');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 12, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Deportología', 'Deportología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 13, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Cirugía General', 'Cirugía General');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true,'2024-09-05', null, 14, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Estética', 'Estética');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 15, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Gastroenterología', 'Gastroenterología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 16, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Hematología', 'Hematología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 17, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Infectología', 'Infectología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 18, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Nefrología', 'Nefrología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 19, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Neumonología', 'Neumonología');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 20, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Obstetricia', 'Obstetricia');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 21, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Psiquiatría', 'Psiquiatría');
INSERT INTO public.specialties(active, created_at, deleted_at, specialty_id, updated_at, create_by, delete_by, update_by, specialty_name, specialty_description) VALUES (true, '2024-09-05', null, 22, null, 'f46917b3-eb0a-4946-b243-5347fb2054a2', null, null,'Urología', 'Urología');
